Class dc.upload.UploadProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="dc.upload.UploadProduction" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="UploadService" Category="" ClassName="dc.upload.UploadService" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
